### ISSUE TITLE
Creosote Bucket impossible

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-2#43] opened 2017-07-05 22:00 UTC
On both version 0.72c and 0.72d I cannot put creosote oil into a bucket.  
I tried crafting with the refined storage system and also with a refined storage fluid grid it's not possible to get a bucket of creosote.  
Also directly from the coke oven there the bucket stays in the top slot instead of filling.  
It's impossible to make treated wood like this.  
Also creosote buckets show in JEI with a broken texture of the fluid. In a portable Thermal Expansion tank it also shows a purple/black squared broken texture and in a drum it shows no texture at all, like the drum was empty.

When right clicking fluid buckets that say "Minecraft Forge" as mod name you don't get to the other uses of that exact fluid, but to all fluid uses from "Minecraft Forge".

**Comment by MythicProjectz** [comment] 2017-07-08 03:41
I can agree with this. People on my server have had the same exact issue. Here is a picture of the broken textures they have. http://prntscr.com/ft1ze0

**Comment by NinjaOukie** [comment] 2017-07-08 12:31
Confirmed that single player has the same issue

**Comment by JustaRandom** [comment] 2017-07-20 11:32
So.... I looked into creosote and there is no recipe (even on creative) for it so it will never work.
You can however put the oil into an universal cell/capsule/can/canister/florb from the tank but cannot be put on the ground.

Problems so far      - When throwing florb on the ground transform into water.
                                - All cells content cannot be put on the ground.
                                - No recipe for creosote bucket.
                                - Bottler does not work with bucket but work with capsule.

Working                  - Transfer from tank to cells and inverted.
                                - If spawn creative creosote oil, no broken texture and can be placed on world.

**Comment by JustaRandom** [comment] 2017-07-28 07:30
After looking for some time at this it seems that there are some problem moving up from the version 0.72 latest to 0.73.
For references: I am using the twitch launcher (ease of use)
                          Was tested with multimc and the twitch launcher

What I did test : 
- Copying all the mods and cfg to multimc (just a plain cp/paste) and launching = work.
- Copying the whole folder from twitch launcher to multimc and launching = problem.
- Multimc with just immersive engineering = work
- Duplicate Modpack on twitch launcher = Mix ( see below )

If duplicating the modpack on the twitch launcher and playing the same instance, there is a problem with the bucket of creosote. But making a new game seems to fix it.

Side note : seems like some cfg from the script does not work as intended .Minetweaker log

[PREINITIALIZATION][CLIENT][ERROR] system: LootTable is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: JEI is already defined in that package
[AVAILABLE][CLIENT][INFO] MineTweaker: Building registry
[AVAILABLE][CLIENT][INFO] MineTweaker: Sucessfully built item registry
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding command minetweaker
[SERVER_ABOUT_TO_START][SERVER][INFO] --- loading edited_recipes.zs ---
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 2 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 2 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 2 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 2 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 2 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Yellorium Seeds
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Acceleration Wand
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Oak Chest
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Red Bed
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Diamond Chip
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Wooden Carving Tool
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Stone Carving Tool
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Iron Carving Tool
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Gold Carving Tool
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Diamond Carving Tool
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Wooden Knife
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Stone Knife
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Iron Knife
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Golden Knife
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 1 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Diamond Knife
[SERVER_ABOUT_TO_START][SERVER][INFO] Removing 3 recipes
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Skillet
[SERVER_ABOUT_TO_START][SERVER][INFO] Adding recipe for Skillet
[SERVER_STOPPING][SERVER][INFO] Server stopping, Scripts are being rolled back!
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Skillet
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Skillet
[SERVER_STOPPING][SERVER][INFO] Restoring 3 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Diamond Knife
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Golden Knife
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Iron Knife
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Stone Knife
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Wooden Knife
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Diamond Carving Tool
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Gold Carving Tool
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Iron Carving Tool
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Stone Carving Tool
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Wooden Carving Tool
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Diamond Chip
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Red Bed
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Oak Chest
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Acceleration Wand
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Removing recipe for Yellorium Seeds
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 2 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 2 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 2 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 2 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 2 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] Restoring 1 recipes
[SERVER_STOPPING][SERVER][INFO] tried to remove command: minetweaker failed. THIS IS NOT AN ERROR!

On a new instance there is no fail (because this is not an error).

**Comment by Boomflex** [comment] 2017-08-08 08:02
Fixed in 0.74

**Closed as completed by Boomflex** 2017-08-08 08:02 UTC
